excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://vpribeiro73.github.io
title: Fucking Awesome
email: vpribeiro@hotmail.com.br
author: vpribeiro73
description: My awesome new site
paginate: 5
google_analytics: 
